"""initial

Revision ID: 5bad0a269789
Revises: 
"""
from alembic import op
import sqlalchemy as sa


revision = "0001"
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('bot_pending_actions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('token', sa.String(length=64), nullable=False),
    sa.Column('channel', sa.String(length=20), nullable=False),
    sa.Column('owner', sa.String(length=100), nullable=False),
    sa.Column('external_message_id', sa.String(length=128), nullable=True),
    sa.Column('action_type', sa.String(length=50), nullable=False),
    sa.Column('payload_json', sa.Text(), nullable=False),
    sa.Column('result_json', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('expires_at', sa.DateTime(), nullable=False),
    sa.Column('processing_at', sa.DateTime(), nullable=True),
    sa.Column('confirmed_at', sa.DateTime(), nullable=True),
    sa.Column('cancelled_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('channel', 'external_message_id')
    )
    op.create_index(op.f('ix_bot_pending_actions_owner'), 'bot_pending_actions', ['owner'], unique=False)
    op.create_index(op.f('ix_bot_pending_actions_token'), 'bot_pending_actions', ['token'], unique=True)
    op.create_table('categories',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('icon', sa.String(length=10), nullable=True),
    sa.Column('sort_order', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('fx_rates',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('rate_date', sa.Date(), nullable=False),
    sa.Column('rate_to_usd', sa.Numeric(precision=14, scale=6), nullable=False),
    sa.Column('fetched_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('currency', 'rate_date')
    )
    op.create_table('stops',
    sa.Column('slug', sa.String(length=80), nullable=False),
    sa.Column('order', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('country', sa.String(length=80), nullable=True),
    sa.Column('country_flag', sa.String(length=16), nullable=True),
    sa.Column('arrival_date', sa.Date(), nullable=True),
    sa.Column('departure_date', sa.Date(), nullable=True),
    sa.Column('currency_code', sa.String(length=3), nullable=True),
    sa.Column('timezone', sa.String(length=64), nullable=True),
    sa.Column('is_transit', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('is_candidate', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('is_flex_margin', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('synced_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('slug')
    )
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=100), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=True),
    sa.Column('whatsapp_wa_id', sa.String(length=50), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('username'),
    sa.UniqueConstraint('whatsapp_wa_id')
    )
    op.create_table('whatsapp_dedupe',
    sa.Column('wamid', sa.String(length=128), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('wamid')
    )
    op.create_index(op.f('ix_whatsapp_dedupe_created_at'), 'whatsapp_dedupe', ['created_at'], unique=False)
    op.create_table('whatsapp_session_states',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('wa_id', sa.String(length=50), nullable=False),
    sa.Column('owner', sa.String(length=100), nullable=False),
    sa.Column('payload_json', sa.Text(), server_default=sa.text("'{}'"), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_whatsapp_session_states_owner'), 'whatsapp_session_states', ['owner'], unique=False)
    op.create_index(op.f('ix_whatsapp_session_states_wa_id'), 'whatsapp_session_states', ['wa_id'], unique=True)
    op.create_table('movements',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('type', sa.String(length=12), server_default=sa.text("'expense'"), nullable=False),
    sa.Column('amount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('currency', sa.String(length=3), server_default=sa.text("'USD'"), nullable=False),
    sa.Column('amount_usd', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('fx_rate', sa.Numeric(precision=14, scale=6), server_default=sa.text("'1.0'"), nullable=False),
    sa.Column('fx_source', sa.String(length=16), server_default=sa.text("'manual'"), nullable=False),
    sa.Column('paid_by', sa.Integer(), nullable=False),
    sa.Column('split', sa.String(length=12), server_default=sa.text("'shared'"), nullable=False),
    sa.Column('description', sa.String(length=255), nullable=True),
    sa.Column('category_id', sa.Integer(), nullable=True),
    sa.Column('stop_slug', sa.String(length=80), nullable=True),
    sa.Column('city_name', sa.String(length=120), nullable=True),
    sa.Column('movement_date', sa.Date(), nullable=False),
    sa.Column('raw_message', sa.Text(), nullable=True),
    sa.Column('created_by', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['category_id'], ['categories.id'], ),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['paid_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_movements_date', 'movements', ['movement_date'], unique=False)
    op.create_index(op.f('ix_movements_paid_by'), 'movements', ['paid_by'], unique=False)
    op.create_index('ix_movements_stop_slug', 'movements', ['stop_slug'], unique=False)
    op.create_index(op.f('ix_movements_type'), 'movements', ['type'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_movements_type'), table_name='movements')
    op.drop_index('ix_movements_stop_slug', table_name='movements')
    op.drop_index(op.f('ix_movements_paid_by'), table_name='movements')
    op.drop_index('ix_movements_date', table_name='movements')
    op.drop_table('movements')
    op.drop_index(op.f('ix_whatsapp_session_states_wa_id'), table_name='whatsapp_session_states')
    op.drop_index(op.f('ix_whatsapp_session_states_owner'), table_name='whatsapp_session_states')
    op.drop_table('whatsapp_session_states')
    op.drop_index(op.f('ix_whatsapp_dedupe_created_at'), table_name='whatsapp_dedupe')
    op.drop_table('whatsapp_dedupe')
    op.drop_table('users')
    op.drop_table('stops')
    op.drop_table('fx_rates')
    op.drop_table('categories')
    op.drop_index(op.f('ix_bot_pending_actions_token'), table_name='bot_pending_actions')
    op.drop_index(op.f('ix_bot_pending_actions_owner'), table_name='bot_pending_actions')
    op.drop_table('bot_pending_actions')
    # ### end Alembic commands ###
